#obj-$(CONFIG_DVB_ARCHOSDIB7070P) += archosdib7070p.o
obj-$(CONFIG_DVB_ARCHOSDIB7070P) += archos_omap_dvb.o

EXTRA_CFLAGS += -Idrivers/media/dvb/dvb-core/ -Idrivers/media/dvb/frontends/

obj-$(CONFIG_DAVINCI_DVB) += davinci_vpfe_dvb.o

EXTRA_CFLAGS += -I$(srctree)/drivers/media/dvb/dvb-core
EXTRA_CFLAGS += -I$(srctree)/drivers/media/dvb/frontends
