/*
 * drivers/media/video/omap/gci/user/test/mt9p012_config.c
 *
 * Sensor config file for testing
 * TI's OMAP3430 Camera ISP - GCI solution
 *
 * Copyright (C) 2007 Texas Instruments.
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published 
 * by the Free Software Foundation version 2.1 of the License.
 *
 * This program is distributed .as is. WITHOUT ANY WARRANTY of any kind,
 * whether express or implied; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 */

extern int issue_sensortrans_reg16_data16(unsigned int data[], int size);

#define SENSOR_WIDTH8	1
#define SENSOR_WIDTH16	2
#define SENSOR_WIDTH32	4

#define SENSOR_WRITE	1
#define SENSOR_READ	0

/* The ID values we are looking for */
#define MT9P012_MOD_ID			0x2800
#define MT9P012_MFR_ID			0x0006

/* Used registers */
#define REG_MODEL_ID			0x0000 
#define REG_REVISION_NUMBER		0x0002
#define REG_MANUFACTURER_ID		0x0003

#define REG_MODE_SELECT			0x0100 
#define REG_IMAGE_ORIENTATION		0x0101 
#define REG_SOFTWARE_RESET		0x0103
#define REG_GROUPED_PAR_HOLD		0x0104

#define REG_FINE_INT_TIME		0x0200
#define REG_COARSE_INT_TIME		0x0202

#define REG_ANALOG_GAIN_GLOBAL		0x0204
#define REG_ANALOG_GAIN_GREENR		0x0206
#define REG_ANALOG_GAIN_RED		0x0208
#define REG_ANALOG_GAIN_BLUE		0x020A
#define REG_ANALOG_GAIN_GREENB		0x020C
#define REG_DIGITAL_GAIN_GREENR		0x020E
#define REG_DIGITAL_GAIN_RED		0x0210
#define REG_DIGITAL_GAIN_BLUE		0x0212
#define REG_DIGITAL_GAIN_GREENB		0x0214

#define REG_VT_PIX_CLK_DIV		0x0300
#define REG_VT_SYS_CLK_DIV		0x0302
#define REG_PRE_PLL_CLK_DIV		0x0304
#define REG_PLL_MULTIPLIER		0x0306
#define REG_OP_PIX_CLK_DIV		0x0308
#define REG_OP_SYS_CLK_DIV		0x030A

#define REG_FRAME_LEN_LINES		0x0340
#define REG_LINE_LEN_PCK		0x0342

#define REG_X_ADDR_START		0x0344
#define REG_Y_ADDR_START		0x0346
#define REG_X_ADDR_END			0x0348
#define REG_Y_ADDR_END			0x034A
#define REG_X_OUTPUT_SIZE		0x034C
#define REG_Y_OUTPUT_SIZE		0x034E
#define REG_X_ODD_INC			0x0382
#define REG_Y_ODD_INC			0x0386

#define REG_SCALING_MODE		0x0400
#define REG_SCALE_M			0x0404
#define REG_SCALE_N			0x0406

#define REG_ROW_SPEED			0x3016
#define REG_RESET_REGISTER		0x301A
#define REG_PIXEL_ORDER			0x3024
#define REG_READ_MODE			0x3040

#define REG_DATAPATH_STATUS		0x306A
#define REG_DATAPATH_SELECT		0x306E

#define REG_RESERVED_MFR_3064		0x3064
#define REG_TEST_PATTERN		0x3070

/*AF D88 register definitions*/
#define CAMAF_D88_NXT_POSN		0x00
#define CAMAF_D88_CUR_POSN		0x01
#define CAMAF_D88_POR_STDBY		0x03
#define CAMAF_D88_THRSH			0x05
#define CAMAF_D88_FREQ_DIV		0x06
#define CAMAF_D88_REV			0x08
#define CAMAF_D88_ID			0x09

#define MT9P012_XCLK_HZ			12000000
#define CAMAF_FREQUENCY_EQ1	((unsigned short)(MT9P012_XCLK_HZ/16000))
#define MID_FOCUS_POS	50
#define MAX_FOCUS_VAL	1023
#define MAX_FOCUS_POS	100

/* Sensor output sizes */
/* Still capture 5 MP */
#define IMAGE_WIDTH_MAX		2592
#define IMAGE_HEIGHT_MAX	1944
/* Still capture 3 MP and down to VGA, using ISP resizer */
#define IMAGE_WIDTH_MIN		2048
#define IMAGE_HEIGHT_MIN	1536
/* Video mode, for D1 NTSC, D1 PAL */
#define VIDEO_WIDTH_2X_BINN	1296
#define VIDEO_HEIGHT_2X_BINN	972
/* Video mode, for VGA, CIF, QVGA */
#define VIDEO_WIDTH_4X_BINN	648
#define VIDEO_HEIGHT_4X_BINN	486
/* (VIDEO_WIDTH_4X_BINN) x (0x10/SCALER) */
/* Video mode, for QCIF, SQCIF */
#define VIDEO_WIDTH_4X_BINN_SCALED	216
#define VIDEO_HEIGHT_4X_BINN_SCALED	162

#define COARSE_INT_TIME_5MP 1300
#define COARSE_INT_TIME_3MP 1300
#define COARSE_INT_TIME_1296 600
#define COARSE_INT_TIME_648 300
#define COARSE_INT_TIME_216 300
	
unsigned int sensor_reset[] = {
	REG_SOFTWARE_RESET,0x01,SENSOR_WIDTH8,SENSOR_WRITE
};
#define SENSOR_RESET_SIZE	4

unsigned int sensor_init[] = {
	REG_RESET_REGISTER,0x10C8,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_GROUPED_PAR_HOLD,0x01,SENSOR_WIDTH8,SENSOR_WRITE,
	REG_ANALOG_GAIN_GREENR,0x0020,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_ANALOG_GAIN_RED,0x0020,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_ANALOG_GAIN_BLUE,0x0020,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_ANALOG_GAIN_GREENB,0x0020,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_DIGITAL_GAIN_GREENR,0x0100,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_DIGITAL_GAIN_RED,0x0100,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_DIGITAL_GAIN_BLUE,0x0100,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_DIGITAL_GAIN_GREENB,0x0100,SENSOR_WIDTH16,SENSOR_WRITE,
	0x3088, 0x6FFB,SENSOR_WIDTH16,SENSOR_WRITE,
	0x308E, 0x2020,SENSOR_WIDTH16,SENSOR_WRITE,
	0x309E, 0x4400,SENSOR_WIDTH16,SENSOR_WRITE,
	0x30D4, 0x9080,SENSOR_WIDTH16,SENSOR_WRITE,
	0x3126, 0x00FF,SENSOR_WIDTH16,SENSOR_WRITE,
	0x3154, 0x1482,SENSOR_WIDTH16,SENSOR_WRITE,
	0x3158, 0x97C7,SENSOR_WIDTH16,SENSOR_WRITE,
	0x315A, 0x97C6,SENSOR_WIDTH16,SENSOR_WRITE,
	0x3162, 0x074C,SENSOR_WIDTH16,SENSOR_WRITE,
	0x3164, 0x0756,SENSOR_WIDTH16,SENSOR_WRITE,
	0x3166, 0x0760,SENSOR_WIDTH16,SENSOR_WRITE,
	0x316E, 0x8488,SENSOR_WIDTH16,SENSOR_WRITE,
	0x3172, 0x0003,SENSOR_WIDTH16,SENSOR_WRITE,
	0x30EA, 0x3F06,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_GROUPED_PAR_HOLD,0x00,SENSOR_WIDTH8,SENSOR_WRITE,
};

#define SENSOR_INIT_SIZE	100

unsigned int sensor_streaming_on[] = {
	REG_MODE_SELECT,0x01,SENSOR_WIDTH8,SENSOR_WRITE
};
#define SENSOR_STREAMING_ON_SIZE	4

unsigned int sensor_streaming_off[] = {
	REG_MODE_SELECT,0x00,SENSOR_WIDTH8,SENSOR_WRITE
};
#define SENSOR_STREAMING_OFF_SIZE	4


unsigned int sensor_enter_video_mode_216[] = {
	REG_GROUPED_PAR_HOLD,0x01,SENSOR_WIDTH8,SENSOR_WRITE,
	REG_VT_PIX_CLK_DIV,8,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_VT_SYS_CLK_DIV, 2,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_PRE_PLL_CLK_DIV,2,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_PLL_MULTIPLIER,126,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_OP_PIX_CLK_DIV,8,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_OP_SYS_CLK_DIV,2,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_RESERVED_MFR_3064, 0x0805,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_X_OUTPUT_SIZE,VIDEO_WIDTH_4X_BINN_SCALED,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_Y_OUTPUT_SIZE,VIDEO_HEIGHT_4X_BINN_SCALED,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_X_ADDR_START,8,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_Y_ADDR_START,8,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_X_ADDR_END,2593,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_Y_ADDR_END,1945,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_READ_MODE,0x04FC,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_FINE_INT_TIME,1794,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_FRAME_LEN_LINES,574,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_LINE_LEN_PCK,2712,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_SCALE_M,0x0030,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_SCALING_MODE,0x0002,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_COARSE_INT_TIME,COARSE_INT_TIME_216,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_GROUPED_PAR_HOLD,0x00,SENSOR_WIDTH8,SENSOR_WRITE,
};
#define SENSOR_ENTER_VIDEO_216_SIZE	88

unsigned int sensor_enter_video_mode_648[] = {
	REG_GROUPED_PAR_HOLD,0x01,SENSOR_WIDTH8,SENSOR_WRITE,
	REG_VT_PIX_CLK_DIV,8,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_PRE_PLL_CLK_DIV,2,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_VT_SYS_CLK_DIV, 2,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_PLL_MULTIPLIER,126,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_OP_PIX_CLK_DIV,8,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_OP_SYS_CLK_DIV,2,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_RESERVED_MFR_3064, 0x0805,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_X_OUTPUT_SIZE,VIDEO_WIDTH_4X_BINN,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_Y_OUTPUT_SIZE,VIDEO_HEIGHT_4X_BINN,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_X_ADDR_START,8,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_Y_ADDR_START,8,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_X_ADDR_END,2593,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_Y_ADDR_END,1945,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_READ_MODE,0x04FC,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_FINE_INT_TIME,1794,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_FRAME_LEN_LINES,574,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_LINE_LEN_PCK,2712,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_SCALING_MODE,0x0000,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_COARSE_INT_TIME,COARSE_INT_TIME_648,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_GROUPED_PAR_HOLD,0x00,SENSOR_WIDTH8,SENSOR_WRITE,
};
#define SENSOR_ENTER_VIDEO_648_SIZE	84

unsigned int sensor_enter_video_mode_1296[] = {
	REG_GROUPED_PAR_HOLD,0x01,SENSOR_WIDTH8,SENSOR_WRITE,
	REG_VT_PIX_CLK_DIV,5,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_PRE_PLL_CLK_DIV,3,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_VT_SYS_CLK_DIV, 1,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_PLL_MULTIPLIER,134,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_OP_PIX_CLK_DIV,10,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_OP_SYS_CLK_DIV,1,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_RESERVED_MFR_3064, 0x0805,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_X_OUTPUT_SIZE,VIDEO_WIDTH_2X_BINN,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_Y_OUTPUT_SIZE,VIDEO_HEIGHT_2X_BINN,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_X_ADDR_START,8,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_Y_ADDR_START,8,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_X_ADDR_END,2597,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_Y_ADDR_END,1949,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_READ_MODE,0x046C,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_FINE_INT_TIME,1794,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_FRAME_LEN_LINES,1061,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_LINE_LEN_PCK,3360,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_SCALING_MODE,0x0000,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_COARSE_INT_TIME,COARSE_INT_TIME_1296,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_GROUPED_PAR_HOLD,0x00,SENSOR_WIDTH8,SENSOR_WRITE,
};
#define SENSOR_ENTER_VIDEO_1296_SIZE	84

unsigned int sensor_enter_image_mode_3MP[] = {
	REG_GROUPED_PAR_HOLD,0x01,SENSOR_WIDTH8,SENSOR_WRITE,
	REG_VT_PIX_CLK_DIV,4,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_PRE_PLL_CLK_DIV,5,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_VT_SYS_CLK_DIV, 1,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_PLL_MULTIPLIER,184,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_OP_PIX_CLK_DIV,8,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_OP_SYS_CLK_DIV,1,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_RESERVED_MFR_3064, 0x0805,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_X_OUTPUT_SIZE,IMAGE_WIDTH_MIN,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_Y_OUTPUT_SIZE,IMAGE_HEIGHT_MIN,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_X_ADDR_START,8,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_Y_ADDR_START,8,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_X_ADDR_END,2599,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_Y_ADDR_END,1951,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_READ_MODE,0x0024,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_FINE_INT_TIME,882,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_FRAME_LEN_LINES,2056,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_LINE_LEN_PCK,5372,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_SCALE_M,0x0014,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_SCALING_MODE,0x0002,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_TEST_PATTERN,0x00,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_COARSE_INT_TIME,COARSE_INT_TIME_3MP,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_GROUPED_PAR_HOLD,0x00,SENSOR_WIDTH8,SENSOR_WRITE,
};
#define SENSOR_ENTER_IMAGE_3MP_SIZE	92

unsigned int sensor_enter_image_mode_5MP[] = {
	REG_GROUPED_PAR_HOLD,0x01,SENSOR_WIDTH8,SENSOR_WRITE,
	REG_VT_PIX_CLK_DIV,4,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_PRE_PLL_CLK_DIV,5,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_VT_SYS_CLK_DIV, 1,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_PLL_MULTIPLIER,184,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_OP_PIX_CLK_DIV,8,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_OP_SYS_CLK_DIV,1,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_RESERVED_MFR_3064, 0x0805,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_X_OUTPUT_SIZE,IMAGE_WIDTH_MAX,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_Y_OUTPUT_SIZE,IMAGE_HEIGHT_MAX,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_X_ADDR_START,8,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_Y_ADDR_START,8,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_X_ADDR_END,2599,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_Y_ADDR_END,1951,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_READ_MODE,0x0024,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_FINE_INT_TIME,882,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_FRAME_LEN_LINES,2056,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_LINE_LEN_PCK,5372,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_SCALE_M,0x0000,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_SCALING_MODE,0x0000,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_COARSE_INT_TIME,COARSE_INT_TIME_5MP,SENSOR_WIDTH16,SENSOR_WRITE,
	REG_GROUPED_PAR_HOLD,0x00,SENSOR_WIDTH8,SENSOR_WRITE,
};
#define SENSOR_ENTER_IMAGE_5MP_SIZE	88

unsigned int sensor_d88_af_init[] = {
	CAMAF_D88_FREQ_DIV,CAMAF_FREQUENCY_EQ1,SENSOR_WIDTH16,SENSOR_WRITE
};
#define SENSOR_D88_AF_INIT_SIZE	4

unsigned int sensor_d88_af_setfocus[] = {
	CAMAF_D88_NXT_POSN,(MID_FOCUS_POS * MAX_FOCUS_VAL) / MAX_FOCUS_POS,SENSOR_WIDTH16,SENSOR_WRITE
};
#define SENSOR_D88_AF_SETFOCUS_SIZE	4

int
mt9p012_reset()
{
	int ret = 0;
	ret = issue_sensortrans_reg16_data16(sensor_reset,SENSOR_RESET_SIZE);
	return ret;
}

int
mt9p012_initial_config()
{
	int ret = 0;
	ret = issue_sensortrans_reg16_data16(sensor_streaming_off,
				SENSOR_STREAMING_OFF_SIZE);
	ret = issue_sensortrans_reg16_data16(sensor_init,
				SENSOR_INIT_SIZE);
	//ret = issue_sensortrans_reg16_data16(sensor_set_clock,
	//			SENSOR_SET_CLOCK_SIZE);
	/* TBD Issue trans for sensor standby mode */
	return ret;
}

int
mt9p012_preview_config(unsigned int width, unsigned height,
			unsigned int left, unsigned int top)
{
	int ret = 0;

	static int scaler_on = 0;
	ret = issue_sensortrans_reg16_data16(sensor_streaming_off,
				SENSOR_STREAMING_OFF_SIZE);
	if (width == VIDEO_WIDTH_4X_BINN_SCALED) {
		ret = issue_sensortrans_reg16_data16
			(sensor_enter_video_mode_216,
			 SENSOR_ENTER_VIDEO_216_SIZE);
	}
	else if (width == VIDEO_WIDTH_4X_BINN) {
		ret = issue_sensortrans_reg16_data16
			(sensor_enter_video_mode_648,
			 SENSOR_ENTER_VIDEO_648_SIZE);
	}
	else if (width == VIDEO_WIDTH_2X_BINN){
		ret = issue_sensortrans_reg16_data16
			(sensor_enter_video_mode_1296,
			 SENSOR_ENTER_VIDEO_1296_SIZE);
	}
	else if (width == IMAGE_WIDTH_MIN){
		ret = issue_sensortrans_reg16_data16
			(sensor_enter_image_mode_3MP,
			 SENSOR_ENTER_IMAGE_3MP_SIZE);
	}
	else {
		ret = issue_sensortrans_reg16_data16
			(sensor_enter_image_mode_5MP,
			 SENSOR_ENTER_IMAGE_5MP_SIZE);
	}
	ret = issue_sensortrans_reg16_data16(sensor_streaming_on,
				SENSOR_STREAMING_ON_SIZE);
	return ret;
}

void 
get_mt9p012_resln(unsigned int width, unsigned int height,
				unsigned int* set_width,
				unsigned int* set_height)
{
		/* TBD 512, 1024 768, 384 has to be appended with
		 * "x" pixels that would be cropped in the ccdc,
		 * preview, resizer modules */
	if (width <= 176) {
		*set_width = VIDEO_WIDTH_4X_BINN_SCALED;
		*set_height = VIDEO_HEIGHT_4X_BINN_SCALED;
	} else if (width <= 352) {
		*set_width = VIDEO_WIDTH_4X_BINN;
		*set_height = VIDEO_HEIGHT_4X_BINN;
	} else if (width <= 720) {
		*set_width = VIDEO_WIDTH_2X_BINN;
		*set_height = VIDEO_HEIGHT_2X_BINN;
	} else if(width <= 2048){ /* For Burst Mode */
		*set_width =  IMAGE_WIDTH_MIN;
		*set_height = IMAGE_HEIGHT_MIN;
	} else {
		*set_width =  IMAGE_WIDTH_MAX;
		*set_height = IMAGE_HEIGHT_MAX;
	}
#if 0
	if (width <= VIDEO_WIDTH_4X_BINN_SCALED) {
		*set_width = VIDEO_WIDTH_4X_BINN_SCALED;
		*set_height = VIDEO_HEIGHT_4X_BINN_SCALED;
	}
	else if (width <= VIDEO_WIDTH_4X_BINN) {
		*set_width = VIDEO_WIDTH_4X_BINN;
		*set_height = VIDEO_HEIGHT_4X_BINN;
	}
	else {
		*set_width = VIDEO_WIDTH_2X_BINN;
		*set_height = VIDEO_HEIGHT_2X_BINN;
	}
#endif
	return;
}


int
mt9p012_focus_initial_config() {
	int ret = 0;
	ret = issue_sensortrans_reg16_data16(sensor_d88_af_init,
				SENSOR_D88_AF_INIT_SIZE);
	ret = issue_sensortrans_reg16_data16(sensor_d88_af_setfocus,
				SENSOR_D88_AF_SETFOCUS_SIZE);
	return ret;
}


